spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: fernando-gontijo
    password: senha123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
