version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  minha_aplicacao:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-exacta
    ports:
      - "8080:8080"
    depends_on:
      - postgres
