version: '3.8'

services:
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready","-U", "user", "-d", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  minha_aplicacao:
    build: .
    container_name: desafio-exacta
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres?user=user&password=password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: "always"



