version: '3.8'

services:
  postgres:
    image: postgres:latest
    platform: linux/x86_64
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


  minha_aplicacao:
    build: .
    container_name: desafio-exacta
    ports:
      - "8080:8080"
    depends_on:
      - postgres



